config/routes.rb
Sana5::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
  resources :health_profiles
  resources :user_health_plans

  resources :user_to_dos do
    collection do
      put :complete
    end
  end

  authenticated :user do
    root to: "user_to_dos#index", as: :authenticated_root
  end

  root to: 'pages#show', id: 'home'

end

app/views/pages/home.html.erb
<div class="outer-container">
  <div class="container">
    <div class="signup-inner-container">
      <div class="signup-text">
        <h1 class="signup-heading">A roadmap to health.</h1>
        <p class="signup-subheading">Improving your health can be confusing. It doesn't need to be.</p>
      </div>
    </div>

    <div class="signup-form">
      <div class="signup-form-inner">
        <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :username, required: true, autofocus: true, placeholder: "Pick a username", label: false %>
          <%= f.input :email, required: true, autofocus: true, placeholder: "Your email", label: false %>
          <%= f.input :password, required: true, placeholder: "Create a password", label: false %>
          <p class="signup-info">Use at least eight characters.</p>
          <%= f.input :password_confirmation, required: true, placeholder: "Confirm password", label: false %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, "Sign up for Sana" %>
          <p class="signup-info">By clicking "Sign up for Sana", you agree to our terms of service and privacy policy.</p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="outer-container" id="blank">
  <div class="container">
    <div class="marketing-inner-container">
      <div class="marketing-text">
        <h1 class="marketing-heading">How it works.</h1>
        <p class="marketing-subheader">Powerful features to make healthy lifestyle more accessible.</p>
      </div>
      <div class="marketing-row">
        <div class="marketing-info-box">
          <div class="marketing-icon">
            <i class="icon-heart-empty icon-4x"></i>
          </div>
          <h2>Set a goal.</h2>
          <p>Calculate your cardiovascular and diabetes risks and choose a health plan that will help you reduce them.</p>
        </div>
        <div class="marketing-info-box">
          <div class="marketing-icon">
            <i class="icon-check icon-4x"></i>
          </div>
          <h2>Complete daily to-dos.</h2>
          <p>Take simple steps towards achieving your goal and do only what really matters to improve your health.</p>
        </div>
        <div class="marketing-info-box">
          <div class="marketing-icon">
            <i class="icon-tasks icon-4x"></i>
          </div>
          <h2>Track your progress.</h2>
          <p>Keep an eye on your progress and personal health profile with performance graphs.</p>
        </div>
      </div>
    </div>
  </div>
</div>