config/routes.rb
Sana5::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
  resources :health_profiles
  resources :user_health_plans

  resources :user_to_dos do
    collection do
      put :complete
    end
  end

  authenticated :user do
    root to: "user_to_dos#index", as: :authenticated_root
  end

  root to: 'pages#show', id: 'home'

end

app/views/layouts/_menu.html.erb
<div class="gn-container">
  <ul id="gn-menu" class="gn-menu-main">
<% if user_signed_in? && current_user.health_plan.present?%>
    <li class="gn-trigger">
      <a class="gn-icon gn-icon-menu"><span>Menu</span></a>
      <nav class="gn-menu-wrapper">
        <div class="gn-scroller">
          <ul class="gn-menu">
<!--             <li>
              <%= link_to root_path do %>
                <i class="gn-icon icon-home"></i>
                <span>Home</span>
              <% end %>
            </li> -->
            <li>
              <%= link_to health_profiles_path do %>
                <i class="gn-icon icon-dashboard"></i>
                <span>Dashboard</span>
              <% end %>
            </li>
            <li>
              <%= link_to user_health_plan_path(current_user.user_health_plan) do %>
                <i class="gn-icon icon-medkit"></i>
                <span>Health Plan</span>
              <% end %>
            </li>
            <li>
              <%= link_to edit_health_profile_path(current_user.health_profiles.last) do %>
                <i class="gn-icon icon-edit"></i>
                <span>Update Health Profile</span>
              <% end %>
            </li>
            <li>
              <%= link_to user_to_dos_path do %>
                <i class="gn-icon icon-ok"></i>
                <span>Daily Checklist</span>
              <% end %>
            </li>
          </ul>
        </div><!-- /gn-scroller -->

      </nav>
    </li>
    <% end %>

    <% if user_signed_in? %>
      <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <li class ="gn-username"><%= current_user.username %></li>
    <% else %>
      <li class="gn-logo">Sana</li>
      <li class="gn-login"><%= link_to "Login", new_user_session_path %></li>
      <% end %>

  </ul>
</div><!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <title>SANA</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

  </head>
  <body>

  <!--   <% if !user_signed_in? %>

      <li><%= link_to "Login", new_user_session_path %></li>
      <% end %> -->
    <%= render 'layouts/menu' %>

    <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: name %>
      <% end -%>
    <%= yield %>

    <script>
      new gnMenu( document.getElementById( 'gn-menu' ) );
    </script>

  </body>
</html>